version: '3.8'

services:
  api:
    image: javieerr/monkeyapi:latest
    container_name: monkeyapi
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URL_DOCKER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_USER=${SMTP_USER}
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
    build: .
    ports: 
      - "3000:3000"
    env_file:
      - .env  # Asegúrate de que el archivo .env esté presente en la raíz del proyecto
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
